language: java
install: true

sudo: false

before_install:
  - chmod +x gradlew
  
stages:
  - name: build
  - name: snapshot
    if: tag IS blank
  - name: release
    if: tag IS present
    
jobs:
  include:
    - stage: build
      script: ./gradlew build
    - stage: snapshot
      script: ./gradlew artifactoryPublish -x test -Dsnapshot=true -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER
    - stage: release
      script: ./gradlew bintrayUpload -x test -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER